magephp:
    log_dir: ./../../var/logs/mage
    environments:
        prod:
            user: root
            branch: master
            from: ./
            host_path: /var/www/html
            releases: 3
            exclude:
                - ./var/cache/*
                - ./var/log/*
                - ./web/app_dev.php
                - ./node_modules/*
            hosts:
                - eidson.info
            pre-deploy:
                - git/update
                - composer/install
                - composer/dump-autoload
            on-deploy:
                - symfony/cache-clear: { env: 'prod' }
                - symfony/cache-warmup: { env: 'prod' }
                - symfony/assets-install: { env: 'prod' }